#!/usr/bin/env bash
# Reject commits whose author email is not the maintainer identity.
# Install: cp config/pre-commit-check-author .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit

allowed='tearodactylus@gmail.com'
author_email="$(git var GIT_AUTHOR_IDENT | sed -n 's/.*<\([^>]*\)>.*/\1/p')"

if [[ "$author_email" != "$allowed" ]]; then
  echo "pre-commit: author email must be <$allowed>, got <$author_email>" >&2
  echo "Run: bash config/git-author-setup.sh \"$(git rev-parse --show-toplevel)\"" >&2
  exit 1
fi
